var urls = {
    sign_in : "/sign-in",
    sign_up : "/sign-up",
    phone : "/phone",
    options : "/options",
    user_story : "/user-story",
    finger_print : "finger-print",
    iris : "iris",
    apply_for : "/apply-for-",
    check_eligibility : "/check-eligibilty",
    apply_service : "/apply-service",
    category : "/?category",
    service : "&service",
    service_id : "service_id",
    survey_id : "userapp_survey_id",
    txn_id : "userapp_txn_id",
    user_service_id : "userapp_service_id",
    documents : "/documents",
    billing_address : "/billing-address",
    enter_aadhaar : "/enter-aadhaar",
    asking_aadhaar : "/asking-aadhaar",
    having_aadhaar : "/having-aadhaar",
    applicant_details : "/applicant-details",
    categories : "/categories",
    aadhaar : "/aadhaar",
    otp : "/otp",
    create_password : "/create-password",
    forgot_password : "/forgot-password",
    user : "/user",
    home : "/home",
    self_declaration : "/self-declaration",
    thank_you : "/thank-you",
    about_us : "/aboutus",
    contact_us : "/contactus",
    media : "/media",
    career : "/career",
    faq : "/faq",
    terms_and_conditions: "/terms_conditions",
    privacy_policy : "/privacy-policy",
    congratulation : "/application-status",
    not_eligible : "/not-eligible",
    dashboard : "/dashboard",
    facebook : "https://www.facebook.com/network/",
    twitter : "https://twitter.com/network",
    linkedIn : "https://in.linkedin.com/company/network",
    app_store : "https://play.google.com/store/apps/details?id=network.com.network",
    save_and_confirm_application : "/save-and-confirm-application",
    translation : "http://staging.network.co.in/translation/",
    url_array_defaultbehaviour:[],
    host_url : "?hosturl=",
    user_details : "/user-details",
    family_member : "/family-member",
    member : "/member",
    application_type : "/application-type",
}

urls.url_array_defaultbehaviour.push(urls.check_eligibility);
urls.url_array_defaultbehaviour.push(urls.apply_service);

export default urls;
